<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class AdminUserSeeder extends Seeder
{
    public function run(): void
    {
        User::updateOrCreate([
            'email' => 'admin@gmail.com',
        ], [
            'name' => 'Admin User',
            'full_name' => 'Admin User',
            'password' => Hash::make('Admin@123'),
            'role' => 'admin',
            'status' => 'active',
            'email_verified_at' => now(),
        ]);

        $members = [
            [
                'name' => 'Maria Concepcion Santos',
                'full_name' => 'Maria Concepcion Santos',
                'email' => 'maria.santos@example.com',
                'school_id' => '2026-0001',
                'nsrc_serial_number' => 'NSRC-2026-0001',
                'college' => 'College of Information Sciences and Computing',
                'major' => 'BSIT',
                'year_level' => '3A',
                'primary_competency' => 'Web Software Tools',
                'gender' => 'Female',
                'status' => 'active',
            ],
            [
                'name' => 'Juan Miguel Dela Cruz',
                'full_name' => 'Juan Miguel Dela Cruz',
                'email' => 'juan.delacruz@example.com',
                'school_id' => '2026-0002',
                'nsrc_serial_number' => 'NSRC-2026-0002',
                'college' => 'College of Information Sciences and Computing',
                'major' => 'BSIT',
                'year_level' => '3B',
                'primary_competency' => 'Network Administration',
                'gender' => 'Male',
                'status' => 'active',
            ],
            [
                'name' => 'Isabella Marie Reyes',
                'full_name' => 'Isabella Marie Reyes',
                'email' => 'isabella.reyes@example.com',
                'school_id' => '2026-0003',
                'nsrc_serial_number' => 'NSRC-2026-0003',
                'college' => 'College of Information Sciences and Computing',
                'major' => 'BSIT',
                'year_level' => '3C',
                'primary_competency' => 'Database Management',
                'gender' => 'Female',
                'status' => 'active',
            ],
            [
                'name' => 'Carlos Andres Bautista',
                'full_name' => 'Carlos Andres Bautista',
                'email' => 'carlos.bautista@example.com',
                'school_id' => '2026-0004',
                'nsrc_serial_number' => 'NSRC-2026-0004',
                'college' => 'College of Information Sciences and Computing',
                'major' => 'BSIT',
                'year_level' => '3A',
                'primary_competency' => 'Cybersecurity',
                'gender' => 'Male',
                'status' => 'active',
            ],
            [
                'name' => 'Sofia Lorraine Gonzales',
                'full_name' => 'Sofia Lorraine Gonzales',
                'email' => 'sofia.gonzales@example.com',
                'school_id' => '2026-0005',
                'nsrc_serial_number' => 'NSRC-2026-0005',
                'college' => 'College of Information Sciences and Computing',
                'major' => 'BSIT',
                'year_level' => '3B',
                'primary_competency' => 'UI/UX Design',
                'gender' => 'Female',
                'status' => 'active',
            ],
            [
                'name' => 'Miguel Angelo Villanueva',
                'full_name' => 'Miguel Angelo Villanueva',
                'email' => 'miguel.villanueva@example.com',
                'school_id' => '2026-0006',
                'nsrc_serial_number' => 'NSRC-2026-0006',
                'college' => 'College of Information Sciences and Computing',
                'major' => 'BSIT',
                'year_level' => '3C',
                'primary_competency' => 'Attendance Operations',
                'gender' => 'Male',
                'status' => 'active',
            ],
            [
                'name' => 'Angela Kristina Mercado',
                'full_name' => 'Angela Kristina Mercado',
                'email' => 'angela.mercado@example.com',
                'school_id' => '2026-0007',
                'nsrc_serial_number' => 'NSRC-2026-0007',
                'college' => 'College of Information Sciences and Computing',
                'major' => 'BSIT',
                'year_level' => '3A',
                'primary_competency' => 'Quality Assurance',
                'gender' => 'Female',
                'status' => 'active',
            ],
            [
                'name' => 'Jose Emmanuel Ramos',
                'full_name' => 'Jose Emmanuel Ramos',
                'email' => 'jose.ramos@example.com',
                'school_id' => '2026-0008',
                'nsrc_serial_number' => 'NSRC-2026-0008',
                'college' => 'College of Information Sciences and Computing',
                'major' => 'BSIT',
                'year_level' => '3B',
                'primary_competency' => 'Technical Support',
                'gender' => 'Male',
                'status' => 'active',
            ],
            [
                'name' => 'Patricia Isabel Sarmiento',
                'full_name' => 'Patricia Isabel Sarmiento',
                'email' => 'patricia.sarmiento@example.com',
                'school_id' => '2026-0009',
                'nsrc_serial_number' => 'NSRC-2026-0009',
                'college' => 'College of Information Sciences and Computing',
                'major' => 'BSIT',
                'year_level' => '3C',
                'primary_competency' => 'Web Software Tools',
                'gender' => 'Female',
                'status' => 'active',
            ],
            [
                'name' => 'Daniel Lorenzo Fernandez',
                'full_name' => 'Daniel Lorenzo Fernandez',
                'email' => 'daniel.fernandez@example.com',
                'school_id' => '2026-0010',
                'nsrc_serial_number' => 'NSRC-2026-0010',
                'college' => 'College of Information Sciences and Computing',
                'major' => 'BSIT',
                'year_level' => '3A',
                'primary_competency' => 'System Administration',
                'gender' => 'Male',
                'status' => 'active',
            ],
            [
                'name' => 'Bianca Marie Lopez',
                'full_name' => 'Bianca Marie Lopez',
                'email' => 'bianca.lopez@example.com',
                'school_id' => '2026-0011',
                'nsrc_serial_number' => 'NSRC-2026-0011',
                'college' => 'College of Information Sciences and Computing',
                'major' => 'BSIT',
                'year_level' => '3B',
                'primary_competency' => 'Database Management',
                'gender' => 'Female',
                'status' => 'active',
            ],
            [
                'name' => 'Kristoffer John Aquino',
                'full_name' => 'Kristoffer John Aquino',
                'email' => 'kristoffer.aquino@example.com',
                'school_id' => '2026-0012',
                'nsrc_serial_number' => 'NSRC-2026-0012',
                'college' => 'College of Information Sciences and Computing',
                'major' => 'BSIT',
                'year_level' => '3C',
                'primary_competency' => 'Network Administration',
                'gender' => 'Male',
                'status' => 'active',
            ],
            [
                'name' => 'Camille Andrea Castillo',
                'full_name' => 'Camille Andrea Castillo',
                'email' => 'camille.castillo@example.com',
                'school_id' => '2026-0013',
                'nsrc_serial_number' => 'NSRC-2026-0013',
                'college' => 'College of Information Sciences and Computing',
                'major' => 'BSIT',
                'year_level' => '3A',
                'primary_competency' => 'UI/UX Design',
                'gender' => 'Female',
                'status' => 'suspended',
            ],
            [
                'name' => 'Rafael Luis Garcia',
                'full_name' => 'Rafael Luis Garcia',
                'email' => 'rafael.garcia@example.com',
                'school_id' => '2026-0014',
                'nsrc_serial_number' => 'NSRC-2026-0014',
                'college' => 'College of Information Sciences and Computing',
                'major' => 'BSIT',
                'year_level' => '3B',
                'primary_competency' => 'Cybersecurity',
                'gender' => 'Male',
                'status' => 'active',
            ],
            [
                'name' => 'Member User',
                'full_name' => 'Member User',
                'email' => 'member@gmail.com',
                'school_id' => '2026-0015',
                'nsrc_serial_number' => 'NSRC-2026-0015',
                'college' => 'College of Information Sciences and Computing',
                'major' => 'BSIT',
                'year_level' => '3C',
                'primary_competency' => 'Technical Support',
                'gender' => 'Male',
                'status' => 'active',
            ],
            [
                'name' => 'Suspended Member',
                'full_name' => 'Suspended Member',
                'email' => 'suspended@gmail.com',
                'school_id' => '2026-0016',
                'nsrc_serial_number' => 'NSRC-2026-0016',
                'college' => 'College of Information Sciences and Computing',
                'major' => 'BSIT',
                'year_level' => '3C',
                'primary_competency' => 'Attendance Operations',
                'gender' => 'Male',
                'status' => 'suspended',
            ],
        ];

        $password = Hash::make('Member@123');

        foreach ($members as $member) {
            User::updateOrCreate(
                ['email' => $member['email']],
                array_merge($member, [
                    'password' => $password,
                    'role' => 'member',
                    'email_verified_at' => now(),
                ])
            );
        }
    }
}
