<?php

namespace App\Listeners;

use App\Models\AuditLog;

class LogReportGenerated
{
    public function handle($event): void
    {
        $user = $event->user ?? auth()->user();
        $reportName = $event->reportName ?? $event->report ?? 'Report';
        $userName = $user?->name ?? 'System';

        AuditLog::create([
            'user_id'    => $user?->id,
            'full_name'  => $user?->full_name ?? $user?->name ?? 'System',
            'type'       => 'OPERATIONS',
            'action'     => 'Report Generated',
            'details'    => "{$reportName} generated by {$userName}.",
            'ip_address' => request()->ip(),
            'user_agent' => request()->userAgent(),
            'timestamp'  => now(),
        ]);
    }
}
